# Generated by Django 6.0.6 on 2026-09-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_github_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='github_access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
