"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.ngrok-free.app', '.ngrok.io', 'obedient-unrigged-impish.ngrok-free.dev']

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://0.0.0.0:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites', # required for django-allauth 

    # global
    'corsheaders',
    'debug_toolbar',
    'django_filters',
    'channels',

    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt.token_blacklist',
    'dj_rest_auth',
    'dj_rest_auth.registration',

    # django-allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # local
    'config',
    'drf_spectacular',

    'apps.accounts',
    'apps.management',
    'apps.notifications',
    'apps.analytics',
    'apps._github',
]

SITE_ID = 1

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
# --- THROTTLING SETTINGS ---
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',       # Anonim foydalanuvchilar uchun
        'rest_framework.throttling.UserRateThrottle',       # Tizimga kirgan foydalanuvchilar uchun
        'rest_framework.throttling.ScopedRateThrottle',     # Aniq view'lar uchun maxsus limitlar
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',        # Anonim foydalanuvchilar kuniga max 100 so'rov
        'user': '1000/day',       # Tizimdagi foydalanuvchilar kuniga max 1000 so'rov
        
        # Sensitive endpoint'lar uchun maxsus scopelar:
        'auth_login': '5/minute',    # Login uchun daqiqasiga 5 ta urinish (Brute-force'ga qarshi)
        'auth_register': '3/hour',   # Ro'yxatdan o'tish uchun soatiga 3 ta urinish
    }
}

AUTHENTICATION_BACKENDS = [
    # Django standart admin paneliga kirish uchun (username orqali)
    'django.contrib.auth.backends.ModelBackend',

    # Django-allauth orqali email bilan kirish uchun maxsus backend
    'allauth.account.auth_backends.AuthenticationBackend',
]

GITHUB_CLIENT_ID = config('GITHUB_CLIENT_ID')
GITHUB_CLIENT_SECRET = config('GITHUB_CLIENT_SECRET')
BACKEND_URL = config('BACKEND_URL', default='http://127.0.0.1:8000').rstrip('/')
GITHUB_WEBHOOK_URL = config(
    'GITHUB_WEBHOOK_URL',
    default=f'{BACKEND_URL}/api/github/webhook/',
).rstrip('/') + '/'
GITHUB_REDIRECT_URI = config(
    'GITHUB_REDIRECT_URI',
    default=f'{BACKEND_URL}/api/github/callback/',
)
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000').rstrip('/')

SOCIAL_AUTH_GITHUB_SCOPE = ['repo', 'admin:repo_hook']

# dj-rest-auth sozlamalari
REST_USE_JWT = True

REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': 'my-app-auth',
    'JWT_AUTH_REFRESH_COOKIE': 'my-app-refresh-token',
    'JWT_AUTH_HTTPONLY': True,  # Buni True qilsangiz, token faqat cookie ichida ketadi, response toza chiqadi
    'SESSION_LOGIN': False,

    'REGISTER_SERIALIZER': 'apps.accounts.serializers.CustomRegisterSerializer',
    'USER_DETAILS_SERIALIZER': 'apps.accounts.serializers.CustomUserDetailSerializer',
    'JWT_SERIALIZER': 'apps.accounts.serializers.CustomJWTSerializer',

}

# JWT_AUTH_COOKIE = 'my-app-auth',
# JWT_AUTH_REFRESH_COOKIE = 'my-app-refresh-token'

ACCOUNT_EMAIL_VERIFICATION = 'none' # email verification is optional. (if verification requiered -> mandatory)
ACCOUNT_LOGIN_METHODS = {'username'}
ACCOUNT_SIGNUP_FIELDS = ['email', 'username*', 'password1*', 'password2*']

from datetime import timedelta

SIMPLE_JWT = {
    # Access token lifespan (short-lived for security)
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=27),
    
    # Refresh token lifespan (longer-lived to get new access tokens)
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    
    # Enables automatic rotation of refresh tokens upon use
    "ROTATE_REFRESH_TOKENS": True,
    
    # Places used refresh tokens into a blacklist (requires token_blacklist app)
    "BLACKLIST_AFTER_ROTATION": True,
}


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

INTERNAL_IPS = ["127.0.0.1"]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'ATOMIC_REQUESTS': True
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'accounts.CustomUser'


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

SPECTACULAR_SETTINGS = {
    'TITLE': 'Promer API',
    'DESCRIPTION': 'API documentation for Promer',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}


GITHUB_WEBHOOK_SECRET = config('GITHUB_WEBHOOK_SECRET') # You can generate a secure secret key for this

if DEBUG:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }
# Production uchun
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [config('REDIS_URL', default='redis://localhost:6379/0')],
            },
        },
    }


"""
EMAIL CONFIGURATIONS
"""
DEFAULT_FROM_EMAIL = 'dav2danderson@gmail.com'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'