# Generated by Django 6.0.6 on 2026-07-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_task_slug_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.RemoveIndex(
            model_name='application',
            name='management__is_dele_35e2e0_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='management__is_dele_7d47a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='management__is_dele_b977a6_idx',
        ),
        migrations.AddField(
            model_name='application',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
