# Generated by Django 6.0.6 on 2026-07-10 12:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_project_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='management.project')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Deparments',
            },
        ),
        migrations.CreateModel(
            name='DepartmentMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('back-end developer', 'Back-end Developer'), ('front-end developer', 'Front-end Developer'), ('mobile developer', 'Mobile Developer'), ('data analyst', 'Data Analyst'), ('web designer', 'Web Designer'), ('cybersecurity specialist', 'Cybersecurity Specialist'), ('fullstack developer', 'Fullstack Developer'), ('software engineer', 'Software Engineer'), ('sales director', 'Sales Director'), ('sales manager', 'Sales Manager'), ('sales development representative', 'Sales Development Representative'), ('business development representative', 'Business Development Representative'), ('account executive', 'Account Executive'), ('sales specialist', 'Sales Specialist'), ('account manager', 'Account Manager'), ('customer success manager', 'Customer Success Manager'), ('vp of sales', 'VP of Sales'), ('cfo', 'CFO (Chief Financial Officer)'), ('fp&a analyst', 'FP&A Analyst'), ('chief accountant', 'Chief Accountant'), ('billing specialist', 'Billing Specialist'), ('accounts receivable', 'Accounts Receivable'), ('cmo', 'CMO (Chief Marketing Officer)'), ('product marketing manager', 'Product Marketing Manager'), ('seo specialist', 'SEO Specialist'), ('content manager', 'Content Manager'), ('copywriter', 'Copywriter'), ('smm specialist', 'SMM Specialist'), ('email marketing specialist', 'Email Marketing Specialist'), ('marketing analyst', 'Marketing Analyst'), ('brand/graphic designer', 'Brand/Graphic Designer')], max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_members', to='management.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('department', 'user')},
            },
        ),
        migrations.AddField(
            model_name='department',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='departments', through='management.DepartmentMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
