# Generated by Django 6.0.6 on 2026-07-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_department_departmentmember_department_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
