# Generated by Django 6.0.7 on 2026-07-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_taskcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
