# Generated by Django 6.0.6 on 2026-07-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_application_status_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
