# Generated by Codex on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_project_github_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('pending_approval', 'Pending Approval'), ('done', 'Done')], default='pending', max_length=20),
        ),
    ]
