# Generated by Django 6.0.6 on 2026-07-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_task_pending_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
