# Generated by Django 6.0.6 on 2026-07-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_department_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentMember',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.CharField(blank=True, help_text='For example: Dav2dAnderson/project', max_length=200, null=True),
        ),
    ]
