# Generated by Django 6.0.6 on 2026-08-07 04:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_remove_departmentmember_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('backend_developer', 'Back-end Developer'), ('frontend_developer', 'Front-end Developer'), ('mobile_developer', 'Mobile Developer'), ('fullstack_developer', 'Fullstack Developer'), ('devops_engineer', 'DevOps Engineer'), ('data_analyst', 'Data Analyst'), ('ui_ux_designer', 'UI/UX Designer'), ('project_manager', 'Project Manager'), ('team_lead', 'Team Lead'), ('qa_engineer', 'QA Engineer')], max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='management.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['is_deleted'], name='management__is_dele_faf515_idx'), models.Index(fields=['project', 'role'], name='management__project_5c5c9d_idx')],
                'unique_together': {('project', 'user')},
            },
        ),
    ]
