# Generated by Django 6.0.6 on 2026-08-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_projectmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='role',
            field=models.CharField(choices=[('backend_developer', 'Back-end Developer'), ('frontend_developer', 'Front-end Developer'), ('mobile_developer', 'Mobile Developer'), ('fullstack_developer', 'Fullstack Developer'), ('devops_engineer', 'DevOps Engineer'), ('data_analyst', 'Data Analyst'), ('ui_ux_designer', 'UI/UX Designer'), ('project_manager', 'Project Manager'), ('team_lead', 'Team Lead'), ('qa_engineer', 'QA Engineer')], default=1, max_length=60),
            preserve_default=False,
        ),
    ]
